### PR TITLE
Adds quick and dirty rake task to delete stories after 1 month.

### PR DESCRIPTION
**Pull request by wjdix**
There was talk about allowing the ability to stop a story from being deleted. Should be easy enough to implement that by updating the relevant scope.

This will require a change to the deployment to run another scheduled task.

### CODE REVIEW

**Comment by drewolson** [comment]
This looks like a good start. A few questions:

* Does this also delete the associated comments?
* Will the karma earned from stories remain after they're deleted?

**Comment by wjdix** [comment]
Karma should remain, it's cached on users. There is a method on `User` which will recalculate karma based on votes. It would result in karma being lost if it were called after stories were deleted. _However_, afaict it never gets called.

**Comment by wjdix** [comment]
With these changes `User.recalculate_all_karma!` probably doesn't make sense anymore. Perhaps, it should be deleted, but I don't feel strongly.

**Review by drewolson — APPROVED** [review]
💯 I'd be 👍 for removing `User.recalculate_all_karma!`

**Pull request merged**
